/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d6",
        "on-primary-fixed": "#001945",
        "on-primary": "#ffffff",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-surface-variant": "#424653",
        "tertiary-container": "#a63b01",
        "secondary": "#CB9C4E",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#233144",
        "surface-variant": "#d5e3fc",
        "on-background": "#0d1c2e",
        "secondary-fixed-dim": "#77da9f",
        "primary": "#00A556",
        "inverse-primary": "#b0c6ff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#ffcebc",
        "on-tertiary-fixed-variant": "#7f2b00",
        "tertiary-fixed": "#ffdbce",
        "secondary-container": "#90f4b7",
        "on-surface": "#0d1c2e",
        "primary-fixed-dim": "#b0c6ff",
        "surface-container-highest": "#d5e3fc",
        "tertiary": "#7f2b00",
        "tertiary-fixed-dim": "#ffb599",
        "surface-container": "#e6eeff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#93f7ba",
        "outline": "#737785",
        "on-secondary-fixed-variant": "#00522f",
        "on-secondary-container": "#007144",
        "error": "#ba1a1a",
        "on-primary-container": "#ccd8ff",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "surface-tint": "#0958ca",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#00419d",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed": "#002110",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-dim": "#ccdbf3",
        "on-error-container": "#93000a",
        "primary-fixed": "#d9e2ff",
        "on-tertiary-fixed": "#370e00",
        "primary-container": "#0a58ca",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "margin-mobile": "16px",
        lg: "48px",
        md: "24px",
        gutter: "24px",
        xl: "80px",
        sm: "12px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
